name: Deploy via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          server: 102.212.247.186  # Your host (without sftp:// prefix)
          username: dywsdjdc       # Your username
          password: a6(TrN29Sd#S  # Store password securely
          port: 1624              # Your custom port
          local-path: "dist/*"    # Files to deploy
          remote-path: "/public_html/"  # Target directory
          delete-remote-files: true      # Clears old files
