name: Deploy via FTP

on:
  push:
    branches:
      - main  # Deploy when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # ✅ Upgrade to Node.js 18+ for ReadableStream support

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to cPanel via FTP
        uses: pressidium/lftp-deploy@v1.0.1
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: sftp
          local-dir: dist/  # This is your build directory
          remote-path: "/public_html/"  # Change this if needed
          cleanup: true  # Remove old files before uploading